### ISSUE TITLE
add image support for the pushsafer plugin

### ISSUE THREAD

**Issue by appzer** [IndigoDomotics/indigo-pushsafer#1]
Please add image support (from URL)  for the pushsafer plugin

API description: [https://www.pushsafer.com/en/pushapi](https://www.pushsafer.com/en/pushapi)

Post Parameters
**p** = Image Data URL with Base64-encoded string
**p2** = Image 2 Data URL with Base64-encoded string
**p3** = Image 3 Data URL with Base64-encoded string

Thanks Kevin

**Comment by FlyingDiver** [comment]
Do you plan to supply the base64 string to the plugin, or do you expect the plugin to do the file read and conversion?

**Comment by FlyingDiver** [comment]
It's still not clear to me how large the image can be.  The limits in the FAQ are very low.

**Comment by appzer** [comment]
the whole POST parameters can be 8192KB

**Comment by FlyingDiver** [comment]
OK, finally got the original plugin working.  I was getting 255 or 301 errors, depending on how I did the request.  Finally figured out I needed to be connecting to https://www.pushsafer.com/api, not just pushsafer.com as was in the original code.

**Comment by FlyingDiver** [comment]
Any chance of getting a voucher for some API calls?  I'm going to be using up all the free ones testing the plugin.

**Comment by FlyingDiver** [comment]
Out of API calls..:(

**Comment by appzer** [comment]
i credited some api calls to your account

**Comment by FlyingDiver** [comment]
Thanks!  In final testing now.  Plugin has been upgraded considerably.

**Comment by FlyingDiver** [comment]
Enabled in release 1.1.1.

**Comment by FlyingDiver** [comment]
http://www.indigodomo.com/pluginstore/161/
