### ISSUE TITLE
Please add these new Pushsafer Parameter

### ISSUE THREAD

**Issue by appzer** [IndigoDomotics/indigo-pushsafer#3]
**Confirm**
https://www.pushsafer.com/en/pushapi_ext#API-CR

**Answer Options**
https://www.pushsafer.com/en/pushapi_ext#API-AO

**Answer Force**
https://www.pushsafer.com/en/pushapi_ext#API-AF

**Comment by FlyingDiver** [comment]
Done in release 2022.1.0
